name: vutiendat3601-shop
services:
  mysql:
    image: mysql:8.1.0
    container_name: mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: shop
      MYSQL_ROOT_PASSWORD: 123456Aa@
    networks:
      - default
    volumes:
      - ./database/:/docker-entrypoint-initdb.d/
networks:
  default:
    name: vutiendat3601-shop
