name: shopsinhvien
services:
  backend-v2:
    image: "vutiendat3601/shopsinhvien-backend-v2:latest"
    hostname: "backend-v2"
    env_file: "backend-v2.env"
    networks:
      - default
  proxy:
    image: nginx:latest
    hostname: proxy
    ports:
      - "443:443"
    networks:
      - default
    restart: always
    volumes:
      - "./proxy/nginx.conf:/etc/nginx/conf.d/default.conf"
      - "/etc/letsencrypt/live/apitest.shopsinhvien.io.vn/fullchain.pem:/etc/tls/apitest.shopsinhvien.io.vn/fullchain.pem:ro"
      - "/etc/letsencrypt/live/apitest.shopsinhvien.io.vn/privkey.pem:/etc/tls/apitest.shopsinhvien.io.vn/privkey.pem:ro"
      - "/etc/letsencrypt/live/test.shopsinhvien.io.vn/fullchain.pem:/etc/tls/test.shopsinhvien.io.vn/fullchain.pem:ro"
      - "/etc/letsencrypt/live/test.shopsinhvien.io.vn/privkey.pem:/etc/tls/test.shopsinhvien.io.vn/privkey.pem:ro"
      - "./html/:/usr/share/nginx/html/:ro"
networks:
  default:
    name: shopsinhvien
