spring:
  application:
    name: vutiendat3601 Shop
  datasource:
    url: jdbc:mysql://mysql:3306/shop?useSSL=false&useUnicode=yes&characterEncoding=UTF-8&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: root
    password: 123456Aa@
  flyway:
    enabled: false
  # docker:
  # compose:
  # file: ./compose.yaml
  data:
    rest:
      base-path: /v1
