server:
  port: 8080
  error:
    include-message: always
spring:
  application:
    name: shop-v2
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        "[format_sql]": true
    show-sql: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: vutien.dat.3601@gmail.com
    password: bvsd bsgs ltkf bphx
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
logging:
  level:
    "[org.springframework.security]": DEBUG
springdoc:
  api-docs:
    path: /v2/apidocs
  swagger-ui:
    path: /v2/apidocs.html
app:
  frontendUrl: https://localhost:4200
  jwt:
    validDurationSecond: 86400
  verification:
    login:
      validDurationSecond: 20000
      codeLength: 120
    email:
      validDurationSecond: 30000
      codeLength: 120
    phone:
      validDurationSecond: 30000
      codeLength: 4
    password:
      validDurationSecond: 30000
      codeLength: 120
bussiness:
  vatPercent: 10
