spring:
  application:
    name: shop-v2
  datasource:
    url: jdbc:postgresql://localhost:5332/customer
    username: amigoscode
    password: password
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        # dialect: org.hibernate.dialect.PostgreSQLDialect
        "[format_sql]": true
    show-sql: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: vutien.dat.3601@gmail.com
    password: bvsd bsgs ltkf bphx
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true

springdoc:
  api-docs:
    path: /v2/apidocs
  swagger-ui:
    path: /v2/apidocs.html
app:
  verification:
    login:
      validDurationSecond: 20000
      codeLength: 120
    email:
      validDurationSecond: 30000
      codeLength: 120
    phone:
      validDurationSecond: 30000
      codeLength: 4
    password:
      validDurationSecond: 30000
      codeLength: 120
      