name: Build Backend version 2 Project and containerize to Docker Hub on Merge Request
on:
  pull_request:
    branches:
      - dev
    types:
      - closed
jobs:
  build:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout Backend version 2 codebase
        uses: actions/checkout@v4
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: liberica
          java-version: 21
      - name: Build with Gradle
        working-directory: ./backend-v2
        run: ./gradlew build
      - name: Login to Docker Hub Container Registry
        uses: docker/login-action@v3
        with:
          registry: docker.io
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Set build number
        id: build-number
        run: echo "BUILD_NUMBER=$(date '+%Y%m%d_%H%M%S')" >> $GITHUB_OUTPUT
      - name: Build Docker Image with Jib Gralde Plugin
        working-directory: ./backend-v2
        run: ./gradlew -Papp.docker.tag=${{steps.build-number.outputs.BUILD_NUMBER}} jib
      - name: Docker pull and Compose Up to dev environement
        run: >
          mkdir ~/.ssh && echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa && chmod 600 ~/.ssh/id_rsa
          && ssh -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no vutiendat3601@dev.shopsinhvien.io.vn "
          cd /home/vutiendat3601/shopsinhvien;
          docker compose pull;
          docker compose up -d;
          "

        