name: Build Backend version 2 Project on Pull Request

on:
  pull_request:
    branches:
      - dev

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout project repository
        uses: actions/checkout@v4
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: liberica
          java-version: 21
      - name: Build with Gradle
        working-directory: ./backend-v2
        run: ./gradlew build
