name: Build Backend version 2 Project on Pull Request

on:
  pull_request:
    branches:
      - dev

jobs:
  build:
    runs-on: ubuntu-22.04
    # defaults:
    #   run:
    #     working-directory: ./
    steps:
      - name: Checkout project repository
        uses: actions/checkout@v4
      # - name: Setup Gradle
      # uses: gradle/actions/setup-gradle@v3
      - name: Build with Gradle
        working-directory: ./backend-v2
        run: ./gradlew build
